### ISSUE TITLE
Enhancing data.py

### ISSUE THREAD

**Issue by Goader** [bszlacht/DPTesseract#4]
* add a list of pages (images) to Document (then we can use structures from data.py at the very start)
* add `page` attribute to Cell (maybe Row too)
* add more properties to BBox (returning list of 4 points or (left, top, width, height))
* should we add `page` to Table too? otherwise, how to find two tables on consecutive pages among others for SplittedTableRecognizer?

**Comment by anetaporebska** [comment]
Some of these issues are solved on my splitted-table-model branch, I will commit rest of them today

**Comment by anetaporebska** [comment]
- Mam dodany page_index do Table, pytanie do czego nam indeksy tych stron w Cell i Row? nie wystarczy jak w Table będziemy to wiedzieć?

**Comment by Goader** [comment]
Może być problem jak połączysz tabele z różnych stron. A potrzebuję `page` dla Cell, bo na przykład przy puszczeniu OCR'a dla pewnej komórki potrzebuję wiedzieć z którego zdjęcia wycinać

**Comment by Goader** [comment]
* add `intersect` and `area` to `BBox`

**Comment by Goader** [comment]
implemented

**Comment by Goader** [comment]
implemented
